name: Disclosure Is Beautiful
favicon: null
layout_spectrum: 0.3446258900221437
typography_spectrum: 0.42279048869386315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.46857583592645824
  lightness: 0.24074979266151786
  saturation: 0.13457395625300705
  rhythmicContrast: 0.014683918561786413
purpose: []
