name: Disclosure Is Beautiful
favicon: null
layout_spectrum: 0.74628
typography_spectrum: 0.93565
title: Disclosure Is Beautiful
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#212629'
    - '#f7b2c5'
    - '#8ad8da'
    - '#6a6e70'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
