name: Disclosure Is Beautiful
favicon: null
layout_spectrum: 0.74628
typography_spectrum: 0.93565
title: Disclosure Is Beautiful
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22272b'
    - '#f0f0f0'
    - '#8ad8da'
    - '#8f8f8f'
    - '#dd9bad'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
