name: Disclosure Is Beautiful
favicon: null
layout_spectrum: 0.50652
typography_spectrum: 0.4854
title: Disclosure Is Beautiful
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d8d8'
    - '#000000'
    - '#a8a8a8'
    - '#4b4b4b'
    - '#868686'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
