name: Disclosure Is Beautiful
favicon: null
layout_spectrum: 0.74628
typography_spectrum: 0.93565
title: Disclosure Is Beautiful
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#595959'
    - '#c1c1c1'
    - '#97a0a4'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
